import type { Metadata } from 'next'
import Topbar from '@/components/Topbar/Topbar'
import ThemeContextProvider from '@/contexts/themeContext'
import './globals.css'

export const metadata: Metadata = {
  title: 'Countries Information',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <ThemeContextProvider>
        <body>
          <Topbar />
          {children}
        </body>
      </ThemeContextProvider>
    </html>
  )
}
